export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_ERR = 'ADD_TO_CART_ERR'

export const GET_CART_PRODUCT_REQUEST = 'GET_CART_PRODUCT_REQUEST'
export const GET_CART_PRODUCT_SUCCESS = 'GET_CART_PRODUCT_SUCCESS'
export const GET_CART_PRODUCT_ERR = 'GET_CART_PRODUCT_ERR'

export const DECREASE_FROM_CART_REQUEST = 'DECREASE_FROM_CART_REQUEST'
export const DECREASE_FROM_CART_SUCCESS = 'DECREASE_FROM_CART_SUCCESS'
export const DECREASE_FROM_CART_ERR = 'DECREASE_FROM_CART_ERR'

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_ERR = 'REMOVE_FROM_CART_ERR'
