export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS'
export const LOGIN_USER_ERR = 'LOGIN_USER_ERR'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCESS'
export const REGISTER_USER_ERR = 'REGISTER_USER_ERR'
